### ISSUE TITLE
Selecting whole file and pressing Esc results in blank window

### ISSUE THREAD

**Issue by defphil** [xi-editor/xi-mac#158]
Using default settings on clean build, pressing Command+A selects whole file. After that If I press Esc window is rendered completely blank. Scrolling or clicking inside the Xi window restores content.

**Comment by cmyr** [comment]
great bug, not sure what's going on here.

**Comment by FilipMiletic** [comment]
```
    {
        "name": "select_all",
        "cat": "rpc",
        "ph": "B",
        "ts": 63060850069,
        "pid": 16230,
        "tid": 1021564,
        "args": {
            "xi_sample_id": 79
        }
    },
    {
        "name": "select_all",
        "cat": "rpc",
        "ph": "E",
        "ts": 63060850286,
        "pid": 16230,
        "tid": 1021564,
        "args": {
            "xi_sample_id": 79
        }
    },
```
Standard procedure after selecting all
... `send edit` twice ...
... `handleRaw` twice ...
... `applyUpdate` twice...
... `EditView Update` twice...

And I think pressing Esc produces `cancel_operation`
```
    {
        "name": "cancel_operation",
        "cat": "rpc",
        "ph": "B",
        "ts": 63061873263,
        "pid": 16230,
        "tid": 1021564,
        "args": {
            "xi_sample_id": 84
        }
    },
    {
        "name": "cancel_operation",
        "cat": "rpc",
        "ph": "E",
        "ts": 63061873508,
        "pid": 16230,
        "tid": 1021564,
        "args": {
            "xi_sample_id": 84
        }
    },
```
Again here goes standard procedure.
... `send edit` twice ...
... `handleRaw` twice ...
... `applyUpdate` twice...
... `EditView Update` twice...

But what's interesting is this part here, this is the thing where it gets blank. I am investigating and reading specific source code parts that could be related to this log, but I don't know Swift. I am checking rust-core for now. 

    {
        "name": "blockingGet",
        "cat": "main",
        "ph": "B",
        "ts": 63061885138,
        "pid": 16230,
        "tid": 1021564,
        "args": {
            "xi_sample_id": 89
        }
    },
    {
        "name": "blockingGet",
        "cat": "main",
        "ph": "E",
        "ts": 63061916311,
        "pid": 16230,
        "tid": 1021564,
        "args": {
            "xi_sample_id": 89
        }
    },
    {
        "name": "EditView render",
        "cat": "main",
        "ph": "B",
        "ts": 63064459838,
        "pid": 16230,
        "tid": 1021564,
        "args": {
            "xi_sample_id": 90
        }
    },
    {
        "name": "EditView render",
        "cat": "main",
        "ph": "E",
        "ts": 63064490645,
        "pid": 16230,
        "tid": 1021564,
        "args": {
            "xi_sample_id": 90
        }
    },
    {
        "name": "blockingGet",
        "cat": "main",
        "ph": "B",
        "ts": 63064460073,
        "pid": 16230,
        "tid": 1021564,
        "args": {
            "xi_sample_id": 91
        }
    },
    {
        "name": "blockingGet",
        "cat": "main",
        "ph": "E",
        "ts": 63064490294,
        "pid": 16230,
        "tid": 1021564,
        "args": {
            "xi_sample_id": 91
        }
    }
]
```

Sorry for the lengthy comment, I tried to cut down the logs as much as I could, but didn't want to leave any of the info, maybe some of you guys find it more helpful than I.

**Comment by FilipMiletic** [comment]
Okey, I think It's safe to say that it's not the part of core, but definitely `xi-mac` (I had to go from the bottom upwards 😇). So I checked debug output in Xcode and got this:

```
logging stderr to /Users/phil/Library/Logs/XiEditor/xi_tmp.log
Enabling tracing in core
error loading plugins from "/Users/phil/Library/Application Support/XiEditor/plugins", error:
Error { repr: Os { code: 2, message: "No such file or directory" } }
starting plugins for view-id-1
starting plugin at path "/Users/phil/Library/Developer/Xcode/DerivedData/XiEditor-bzbmsncnrpmqxfeasmxknlhqiuyn/Build/Products/Debug/XiEditor.app/Contents/Resources/plugins/syntect/bin/xi-syntect-plugin"
starting plugin syntect
client: plugin started syntect
syntect using Plain Text
waiting on process 16838
process ended Ok(ExitStatus(ExitStatus(9)))
client: plugin stopped syntect
starting plugins for view-id-3
starting plugin at path "/Users/phil/Library/Developer/Xcode/DerivedData/XiEditor-bzbmsncnrpmqxfeasmxknlhqiuyn/Build/Products/Debug/XiEditor.app/Contents/Resources/plugins/syntect/bin/xi-syntect-plugin"
starting plugin syntect
client: plugin started syntect
syntect using C++
semaphore timeout 31138us timedOut
semaphore timeout 31197us timedOut
semaphore timeout 31180us timedOut
waiting on process 16839
process ended Ok(ExitStatus(ExitStatus(9)))
document missing for view id view-id-3
```

So this is what console log displayed during my reproduction of bug, just running Xcode project, opening Xi, loading file (Obviously C++ file). There I hit command+A to select whole buffer, and then after I hit Esc we have semaphore timeout. So at least we have reduced the scope of the problem. :) I will def. look into it even though I haven't programmed in Swift much. And just as I move the the scroll, rendering is back and semaphore is ended.

**Comment by cmyr** [comment]
Do you know about loading trace files into chrome? When you use 'Debug -> Write Trace' you can open that file in chrome by going to chrome:://tracing. this might make interpreting those files easier.

My suspicion is that 'esc' has some side effect that is confusing the cache; perhaps it is getting cleared, and is waiting for lines that core doesn't know to send.

**Comment by nangtrongvuon** [comment]
The bug occurs not just when selecting the whole document, but just selecting an area of text that is bigger than the current window size. I suspect the side effect may be with EditView's render method instead.

**Comment by nangtrongvuon** [comment]
This has (mysteriously) been fixed by xi-core(?) in this [commit](https://github.com/google/xi-editor/commit/3f1278266e10ab8f9e8b1bf15cd8f5220d0797a5).

**Comment by cmyr** [comment]
interesting, I don't see anything in that commit specifically that should address this, although I don't have trouble believing there was something in this broader set of changes. This was definitely an issue around not properly invalidating after a selection change. @FilipMiletic can you still reproduce this issue on master?

**Comment by FilipMiletic** [comment]
@cmyr I will build it and try to reproduce tomorrow morning and report back!

**Comment by jansol** [comment]
Closing as there haven't been any reports of this occurring any more and I can't reproduce the issue either.
